/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    tutorialSidebar: [
        'intro',
        'prerequisite',
        'changelog',
        'getting-started',
        {
            type: 'category',
            label: 'WordPress Setup',
            items: [
                {
                    type: 'category',
                    label: 'Install Plugins',
                    items: ['wordpress-setup/install-plugins/onesignal'],
                },
            ],
        },
        {
            type: 'category',
            label: 'App Setup',
            items: [
                {
                    type: 'doc',
                    label: 'React Native Setup',
                    id: 'app-setup/react-native-setup',
                },
                {
                    type: 'category',
                    label: 'Firebase setup',
                    link: {
                        type: 'doc',
                        id: 'app-setup/firebase-setup/firebase-setup',
                    },
                    items: [
                        'app-setup/firebase-setup/android-firebase-setup',
                        'app-setup/firebase-setup/ios-firebase-setup',
                    ],
                },
                {
                    type: 'doc',
                    id: 'app-setup/onesignal-setup',
                },
                {
                    type: 'doc',
                    id: 'app-setup/sentry-setup',
                },
            ],
        },
    ],
}

module.exports = sidebars
